kind: pipeline
type: kubernetes
name: default

steps:
  -
    name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  -
    name: lint and test
    image: golang:1.23
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - golangci-lint run ./...
      - go test -cover ./...
      - echo -n $(git describe --tags --abbrev=0) > .tags
  
  # -
  #   name: build and release
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: ghcr_username
  #     password:
  #       from_secret: ghcr_password
  #     registry: ghcr.io
  #     repo: ghcr.io/ravenxwrx/chainkills
  #   when:
  #     branch:
  #       - main
  #     ref:
  #       - refs/tags/v*.*.*